from datetime import date
from uuid import UUID
from fastapi import APIRouter, Depends
from app.core.config import Settings, get_settings
from app.dependencies.auth import get_current_profile, require_admin, require_doctor, require_patient
from app.schemas.auth import Profile
from app.schemas.clinic import AvailabilityCreate, AppointmentCreate, AppointmentReschedule, LeaveCreate, ReasonRequest, SlotResponse, VisitNoteUpsert, DoctorCreate
from app.services.clinic import ClinicService

router=APIRouter()
def service(settings: Settings=Depends(get_settings)): return ClinicService(settings)
@router.get('/auth/me')
async def me(profile: Profile=Depends(get_current_profile)): return profile
@router.get('/doctors')
async def doctors(s: ClinicService=Depends(service)):
    return await s._rows('doctors',is_active='eq.true',select='id,specialty,is_active,profiles(full_name)')
@router.get('/doctors/{doctor_id}/slots',response_model=list[SlotResponse])
async def slots(doctor_id: UUID,date: date,s: ClinicService=Depends(service)): return await s.slots(doctor_id,date)
@router.post('/appointments')
async def book(data: AppointmentCreate, p: Profile=Depends(require_patient), s: ClinicService=Depends(service)): return await s.book(p,data)
@router.get('/appointments/me')
async def my_appointments(p: Profile=Depends(require_patient),s: ClinicService=Depends(service)): return await s.my_appointments(p)
@router.get('/appointments/me/{appointment_id}')
async def my_appointment(appointment_id: UUID,p: Profile=Depends(require_patient),s: ClinicService=Depends(service)): return await s.own_appointment(p,appointment_id)
@router.post('/appointments/me/{appointment_id}/cancel')
async def cancel(appointment_id: UUID,data: ReasonRequest,p: Profile=Depends(require_patient),s: ClinicService=Depends(service)): return await s.cancel(p,appointment_id,data.reason)
@router.post('/appointments/me/{appointment_id}/reschedule')
async def reschedule(appointment_id: UUID,data: AppointmentReschedule,p: Profile=Depends(require_patient),s: ClinicService=Depends(service)): return await s.reschedule(p,appointment_id,data)
@router.get('/doctor/availability')
async def availability(p: Profile=Depends(require_doctor),s: ClinicService=Depends(service)): return await s.availability(p)
@router.post('/doctor/availability')
async def add_availability(data: AvailabilityCreate,p: Profile=Depends(require_doctor),s: ClinicService=Depends(service)): return await s.add_availability(p,data)
@router.put('/doctor/availability/{availability_id}')
async def update_availability(availability_id: UUID,data: AvailabilityCreate,p: Profile=Depends(require_doctor),s: ClinicService=Depends(service)): return await s.update_availability(p,availability_id,data)
@router.delete('/doctor/availability/{availability_id}',status_code=204)
async def delete_availability(availability_id: UUID,p: Profile=Depends(require_doctor),s: ClinicService=Depends(service)): await s.delete_availability(p,availability_id)
@router.get('/doctor/leaves')
async def leaves(p: Profile=Depends(require_doctor),s: ClinicService=Depends(service)): return await s.leaves(p)
@router.post('/doctor/leaves')
async def add_leave(data: LeaveCreate,p: Profile=Depends(require_doctor),s: ClinicService=Depends(service)): return await s.add_leave(p,data)
@router.delete('/doctor/leaves/{leave_id}',status_code=204)
async def delete_leave(leave_id: UUID,p: Profile=Depends(require_doctor),s: ClinicService=Depends(service)): await s.delete_leave(p,leave_id)
@router.get('/doctor/appointments/pending')
async def pending(p: Profile=Depends(require_doctor),s: ClinicService=Depends(service)): return await s.doctor_appointments(p,pending=True)
@router.get('/doctor/schedule')
async def schedule(date: date|None=None,status: str|None=None,p: Profile=Depends(require_doctor),s: ClinicService=Depends(service)): return await s.doctor_appointments(p,day=date,status=status)
@router.post('/doctor/appointments/{appointment_id}/confirm')
async def confirm(appointment_id: UUID,p: Profile=Depends(require_doctor),s: ClinicService=Depends(service)): return await s.doctor_transition(p,appointment_id,'confirmed')
@router.post('/doctor/appointments/{appointment_id}/reject')
async def reject(appointment_id: UUID,data: ReasonRequest,p: Profile=Depends(require_doctor),s: ClinicService=Depends(service)): return await s.doctor_transition(p,appointment_id,'rejected',data.reason)
@router.post('/doctor/appointments/{appointment_id}/complete')
async def complete(appointment_id: UUID,p: Profile=Depends(require_doctor),s: ClinicService=Depends(service)): return await s.doctor_transition(p,appointment_id,'completed')
@router.post('/doctor/appointments/{appointment_id}/no-show')
async def no_show(appointment_id: UUID,p: Profile=Depends(require_doctor),s: ClinicService=Depends(service)): return await s.doctor_transition(p,appointment_id,'no_show')
@router.get('/doctor/appointments/{appointment_id}/visit-note')
async def doctor_note(appointment_id: UUID,p: Profile=Depends(require_doctor),s: ClinicService=Depends(service)): return await s.doctor_note(p,appointment_id)
@router.put('/doctor/appointments/{appointment_id}/visit-note')
async def upsert_note(appointment_id: UUID,data: VisitNoteUpsert,p: Profile=Depends(require_doctor),s: ClinicService=Depends(service)): return await s.upsert_note(p,appointment_id,data.note_text)
@router.get('/appointments/me/{appointment_id}/visit-note')
async def patient_note(appointment_id: UUID,p: Profile=Depends(require_patient),s: ClinicService=Depends(service)): return await s.patient_note(p,appointment_id)
@router.get('/doctor/patients/{patient_id}/history')
async def history(patient_id: UUID,p: Profile=Depends(require_doctor),s: ClinicService=Depends(service)): return await s.patient_history(p,patient_id)
@router.get('/admin/doctors')
async def admin_doctors(_: Profile=Depends(require_admin),s: ClinicService=Depends(service)): return await s.admin_doctors()
@router.post('/admin/doctors')
async def create_doctor(data: DoctorCreate,p: Profile=Depends(require_admin),s: ClinicService=Depends(service)): return await s.create_doctor(p,data)
@router.post('/admin/doctors/{doctor_id}/deactivate')
async def deactivate(doctor_id: UUID,p: Profile=Depends(require_admin),s: ClinicService=Depends(service)): return await s.deactivate_doctor(p,doctor_id)
@router.get('/admin/patients')
async def admin_patients(search: str|None=None,_: Profile=Depends(require_admin),s: ClinicService=Depends(service)): return await s.admin_patients(search)
@router.get('/admin/appointments')
async def admin_appointments(doctor_id: UUID|None=None,date: date|None=None,status: str|None=None,_: Profile=Depends(require_admin),s: ClinicService=Depends(service)): return await s.admin_appointments(doctor_id,date,status)
@router.post('/admin/appointments/{appointment_id}/cancel')
async def admin_cancel(appointment_id: UUID,data: ReasonRequest,p: Profile=Depends(require_admin),s: ClinicService=Depends(service)): return await s.cancel(p,appointment_id,data.reason,admin=True)
@router.get('/admin/dashboard')
async def dashboard(_: Profile=Depends(require_admin),s: ClinicService=Depends(service)): return await s.dashboard()
@router.post('/internal/automation/expire-pending')
async def expire_pending(p: Profile=Depends(require_admin),s: ClinicService=Depends(service)): return {"expired":await s.expire_pending(p.id)}
@router.post('/internal/automation/day-before-reminders')
async def reminders(_: Profile=Depends(require_admin),s: ClinicService=Depends(service)): return {"created":await s.create_day_before_reminders()}
