import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { apiRequest } from '../services/api'
import { adminApi } from '../services/adminApi'
import { Button, Card, EmptyState, ErrorState, Input, LoadingState, Modal, Select, StatCard, StatusBadge, Textarea } from '../components/ui'
import { formatAppointmentDateTime } from '../utils/time'

const statuses = ['pending', 'confirmed', 'completed', 'no_show', 'cancelled']
const messageOf = error => error?.message || 'Unable to complete this request.'
const dateTime = formatAppointmentDateTime
const doctorName = row => row.doctors?.profiles?.full_name || row.profiles?.full_name || 'Clinic doctor'
const patientName = row => row.profiles?.full_name || 'Patient'
const useAdmin = () => { const { session } = useAuth(); return adminApi((path, options) => apiRequest(path, options, session?.access_token)) }
function Notice({ children }) { return children ? <Card className="doctor-notice" role="status">{children}</Card> : null }

export function AdminDashboard() {
  const api = useAdmin(); const [data, setData] = useState(); const [error, setError] = useState('')
  useEffect(() => { api.dashboard().then(setData).catch(error => setError(messageOf(error))) }, [])
  if (!data && !error) return <LoadingState />
  if (error) return <ErrorState>{error}</ErrorState>
  const appointments = data.today_appointments || []; const names = Object.fromEntries(appointments.map(item => [item.doctor_id, doctorName(item)]))
  const totals = statuses.reduce((result, status) => ({ ...result, [status]: appointments.filter(item => item.status === status).length }), {})
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">Clinic operations</p><h2>Today’s overview</h2></div><Link className="button button--primary" to="/admin/appointments">Manage appointments</Link></div><div className="admin-stats">{statuses.map(status => <StatCard key={status} label={status.replace('_', ' ')} value={totals[status]} />)}</div><section><div className="section-heading"><h2>Today’s appointments</h2><Link to="/admin/appointments">View all</Link></div>{appointments.length ? <div className="appointment-list">{appointments.map(item => <Card key={item.id}><StatusBadge status={item.status} /><h3>{patientName(item)}</h3><p>{doctorName(item)} · {dateTime(item.start_at)}</p></Card>)}</div> : <EmptyState>No appointments are scheduled for today.</EmptyState>}</section><section><h2>Per-doctor status counts</h2>{Object.keys(data.per_doctor_counts || {}).length ? <div className="admin-count-grid">{Object.entries(data.per_doctor_counts).map(([id, counts]) => <Card key={id}><h3>{names[id] || 'Clinic doctor'}</h3><div className="count-list">{statuses.map(status => <span key={status}>{status.replace('_', ' ')} <strong>{counts[status] || 0}</strong></span>)}</div></Card>)}</div> : <EmptyState>No per-doctor counts are available for today.</EmptyState>}</section></div>
}

export function AdminDoctors() {
  const api = useAdmin(); const [items, setItems] = useState(); const [form, setForm] = useState({ full_name: '', email: '', specialty: '', phone: '' }); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [deactivating, setDeactivating] = useState(null)
  const refresh = () => api.doctors().then(setItems).catch(error => setError(messageOf(error)))
  useEffect(() => { refresh() }, [])
  const create = async event => { event.preventDefault(); setBusy(true); setError(''); setNotice(''); try { await api.createDoctor({ ...form, phone: form.phone || null }); setForm({ full_name: '', email: '', specialty: '', phone: '' }); setNotice('Doctor created. The secure invitation and password-setup process has been queued.'); await refresh() } catch (error) { setError(messageOf(error)) } finally { setBusy(false) } }
  const deactivate = async () => { setBusy(true); setError(''); try { await api.deactivateDoctor(deactivating.id); setNotice(`${doctorName(deactivating)} is now inactive.`); setDeactivating(null); await refresh() } catch (error) { setError(messageOf(error)) } finally { setBusy(false) } }
  if (!items && !error) return <LoadingState />
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">Team access</p><h2>Doctors</h2></div></div><Card><h3>Add doctor</h3><form className="form-grid admin-form" onSubmit={create}><Input id="doctor-name" label="Full name" value={form.full_name} onChange={event => setForm({ ...form, full_name: event.target.value })} required /><Input id="doctor-email" label="Email" type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} required /><Input id="doctor-specialty" label="Specialty" value={form.specialty} onChange={event => setForm({ ...form, specialty: event.target.value })} required /><Input id="doctor-phone" label="Phone (optional)" value={form.phone} onChange={event => setForm({ ...form, phone: event.target.value })} /><Button loading={busy} type="submit">Create doctor</Button></form></Card><Notice>{notice}</Notice>{error && <ErrorState>{error}</ErrorState>}{!items?.length ? <EmptyState>No doctors have been added yet.</EmptyState> : <div className="admin-card-list">{items.map(item => <Card key={item.id}><div className="appointment-card__heading"><div><StatusBadge status={item.is_active ? 'confirmed' : 'cancelled'} /><h3>{doctorName(item)}</h3><p>{item.specialty}</p><p className="muted-copy">{item.profiles?.email}{item.profiles?.phone ? ` · ${item.profiles.phone}` : ''}</p></div>{item.is_active ? <Button variant="destructive" disabled={busy} onClick={() => setDeactivating(item)}>Deactivate</Button> : <span className="muted-copy">Inactive</span>}</div></Card>)}</div>}<Modal open={Boolean(deactivating)} title="Deactivate doctor" onClose={() => setDeactivating(null)}><p>Deactivate {deactivating && doctorName(deactivating)}? Existing appointments are preserved, but new appointments can no longer be booked.</p><div className="inline-actions"><Button variant="destructive" loading={busy} onClick={deactivate}>Deactivate doctor</Button><Button variant="ghost" onClick={() => setDeactivating(null)}>Cancel</Button></div></Modal></div>
}

export function AdminPatients() {
  const api = useAdmin(); const [items, setItems] = useState(); const [search, setSearch] = useState(''); const [error, setError] = useState('')
  const load = term => api.patients(term).then(setItems).catch(error => setError(messageOf(error)))
  useEffect(() => { load('') }, [])
  if (!items && !error) return <LoadingState />
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">People</p><h2>Patients</h2></div></div><form className="search-row" onSubmit={event => { event.preventDefault(); setError(''); load(search) }}><Input id="patient-search" label="Search name, email, or phone" type="search" value={search} onChange={event => setSearch(event.target.value)} /><Button type="submit">Search</Button></form>{error && <ErrorState>{error}</ErrorState>}{!items?.length ? <EmptyState>No patients match this search.</EmptyState> : <div className="admin-card-list">{items.map(item => <Card key={item.id}><h3>{item.full_name}</h3><p>{item.email}</p>{item.phone && <p>{item.phone}</p>}<p className="muted-copy">{item.is_active ? 'Active account' : 'Inactive account'}</p></Card>)}</div>}</div>
}

export function AdminAppointments() {
  const api = useAdmin(); const [items, setItems] = useState(); const [doctors, setDoctors] = useState([]); const [filters, setFilters] = useState({ doctorId: '', date: '', status: '' }); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [cancelling, setCancelling] = useState(null); const [reason, setReason] = useState('')
  const refresh = values => api.appointments(values || filters).then(setItems).catch(error => setError(messageOf(error)))
  useEffect(() => { refresh(); api.doctors().then(setDoctors).catch(() => setDoctors([])) }, [])
  const cancel = async () => { setBusy(true); setError(''); try { await api.cancelAppointment(cancelling.id, reason); setCancelling(null); setReason(''); setNotice('Appointment cancelled. The server-confirmed schedule has been refreshed.'); await refresh() } catch (error) { setError(messageOf(error)) } finally { setBusy(false) } }
  if (!items && !error) return <LoadingState />
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">Appointment operations</p><h2>Appointments</h2></div></div><div className="filter-row admin-filters"><Select id="admin-doctor-filter" label="Doctor" value={filters.doctorId} onChange={event => setFilters({ ...filters, doctorId: event.target.value })}><option value="">All doctors</option>{doctors.map(doctor => <option key={doctor.id} value={doctor.id}>{doctorName(doctor)}</option>)}</Select><Input id="admin-date-filter" label="Date" type="date" value={filters.date} onChange={event => setFilters({ ...filters, date: event.target.value })} /><Select id="admin-status-filter" label="Status" value={filters.status} onChange={event => setFilters({ ...filters, status: event.target.value })}><option value="">All statuses</option>{['pending', 'confirmed', 'rejected', 'cancelled', 'completed', 'no_show'].map(status => <option key={status} value={status}>{status.replace('_', ' ')}</option>)}</Select><Button onClick={() => { setError(''); refresh() }}>Apply filters</Button></div><Notice>{notice}</Notice>{error && <ErrorState>{error}</ErrorState>}{!items?.length ? <EmptyState>No appointments match these filters.</EmptyState> : <div className="appointment-list">{items.map(item => <Card key={item.id}><div className="appointment-card__heading"><div><StatusBadge status={item.status} /><h3>{patientName(item)}</h3><p>{doctorName(item)} · {dateTime(item.start_at)}</p></div>{['pending', 'confirmed'].includes(item.status) && <Button variant="destructive" disabled={busy} onClick={() => setCancelling(item)}>Cancel appointment</Button>}</div></Card>)}</div>}<Modal open={Boolean(cancelling)} title="Cancel appointment" onClose={() => setCancelling(null)}><p>Cancel this appointment? This is a server-authorized action and cannot be undone here.</p><Textarea id="admin-cancellation-reason" label="Cancellation reason (optional)" value={reason} onChange={event => setReason(event.target.value)} maxLength="500" /><div className="inline-actions"><Button variant="destructive" loading={busy} onClick={cancel}>Confirm cancellation</Button><Button variant="ghost" onClick={() => setCancelling(null)}>Keep appointment</Button></div></Modal></div>
}
