import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { vi } from 'vitest'
import { Appointments, Booking, Detail, Doctors, PatientDashboard } from './PatientPages'
import { formatAppointmentDateTime, formatTime12Hour } from '../utils/time'

const api = { doctors: vi.fn(), slots: vi.fn(), appointments: vi.fn(), detail: vi.fn(), book: vi.fn(), cancel: vi.fn(), reschedule: vi.fn(), note: vi.fn() }
vi.mock('../context/AuthContext', () => ({ useAuth: () => ({ session: { access_token: 'test' } }) }))
vi.mock('../services/patientApi', () => ({ patientApi: () => api }))
const route = (element, url = '/', path = '*') => render(<MemoryRouter initialEntries={[url]}><Routes><Route path={path} element={element}/></Routes></MemoryRouter>)

beforeEach(() => { vi.resetAllMocks() })
afterEach(cleanup)
test('renders active doctors and booking actions', async () => { api.doctors.mockResolvedValue([{ id:'d1', specialty:'Cardiology', profiles:{full_name:'Dr. Chen'} }]); route(<Doctors/>); expect(await screen.findByText('Dr. Chen')).toBeInTheDocument(); expect(screen.getByText('Cardiology')).toBeInTheDocument(); expect(screen.getByRole('link',{name:/book appointment/i})).toBeInTheDocument() })
test('formats appointment slot times for patient display', () => { expect(formatTime12Hour('09:00')).toBe('09:00 AM'); expect(formatTime12Hour('14:30')).toBe('02:30 PM'); expect(formatTime12Hour('12:00')).toBe('12:00 PM'); expect(formatTime12Hour('00:00')).toBe('12:00 AM') })
test('formats appointment timestamps in Asia/Karachi without browser-timezone drift', () => { expect(formatAppointmentDateTime('2026-09-22T05:00:00Z')).toBe('22 Sep 2026, 10:00 AM'); expect(formatAppointmentDateTime('2026-09-22T10:00:00Z')).toBe('22 Sep 2026, 3:00 PM') })
test('renders formatted slots and books with the original backend values', async () => { api.slots.mockResolvedValue([{start_at:'2035-01-01T09:00:00Z',end_at:'2035-01-01T09:30:00Z'}]); api.book.mockResolvedValue({status:'pending'}); route(<Booking/>, '/patient/book/d1', '/patient/book/:doctorId'); fireEvent.change(screen.getByLabelText('Date'),{target:{value:'2035-01-01'}}); fireEvent.click(screen.getByText('Load available times')); const slot=await screen.findByRole('button',{name:'02:00 PM'}); fireEvent.click(slot); fireEvent.click(screen.getByText('Submit request')); await waitFor(()=>expect(api.book).toHaveBeenCalledWith({doctor_id:'d1',start_at:'2035-01-01T09:00:00Z',end_at:'2035-01-01T09:30:00Z'})); expect(await screen.findByText(/Request submitted as Pending/i)).toBeInTheDocument() })
test('shows a booking conflict, clears the stale selection, and reloads slots', async () => { const stale={start_at:'2035-01-01T04:00:00Z',end_at:'2035-01-01T04:30:00Z'}; api.slots.mockResolvedValueOnce([stale]).mockResolvedValueOnce([]); const conflict=Object.assign(new Error('Requested slot is unavailable.'),{status:409}); api.book.mockRejectedValue(conflict); route(<Booking/>, '/patient/book/d1', '/patient/book/:doctorId'); fireEvent.change(screen.getByLabelText('Date'),{target:{value:'2035-01-01'}}); fireEvent.click(screen.getByText('Load available times')); fireEvent.click(await screen.findByRole('button',{name:'09:00 AM'})); fireEvent.click(screen.getByText('Submit request')); expect(await screen.findByText('Requested slot is unavailable.')).toBeInTheDocument(); await waitFor(()=>expect(api.slots).toHaveBeenCalledTimes(2)); expect(screen.queryByText('Submit request')).not.toBeInTheDocument(); expect(api.book).toHaveBeenCalledTimes(1) })
test('clears a stale reschedule selection after a conflict', async () => { const stale={start_at:'2035-01-02T05:00:00Z',end_at:'2035-01-02T05:30:00Z'}; api.slots.mockResolvedValueOnce([stale]).mockResolvedValueOnce([]); api.reschedule.mockRejectedValue(Object.assign(new Error('Appointment could not be rescheduled.'),{status:409})); route(<Booking/>, '/patient/book?appointment=a1&doctor=d1'); fireEvent.change(screen.getByLabelText('Date'),{target:{value:'2035-01-02'}}); fireEvent.click(screen.getByText('Load available times')); fireEvent.click(await screen.findByRole('button',{name:'10:00 AM'})); fireEvent.click(screen.getByText('Submit request')); expect(await screen.findByText('Appointment could not be rescheduled.')).toBeInTheDocument(); await waitFor(()=>expect(api.slots).toHaveBeenCalledTimes(2)); expect(screen.queryByText('Submit request')).not.toBeInTheDocument(); expect(api.reschedule).toHaveBeenCalledTimes(1) })
test('lists appointments and cancels through API then reloads server data', async () => { const appointment={id:'a',doctor_id:'d',start_at:'2035-01-01T09:00:00Z',status:'confirmed',doctors:{specialty:'Cardiology',profiles:{full_name:'Dr. Chen'}}}; api.appointments.mockResolvedValueOnce([appointment]).mockResolvedValueOnce([]); api.cancel.mockResolvedValue({}); route(<Appointments/>); expect(await screen.findByText('Dr. Chen')).toBeInTheDocument(); fireEvent.click(screen.getByText('Cancel')); await waitFor(()=>expect(api.cancel).toHaveBeenCalledWith('a')); expect(await screen.findByText('No appointments yet.')).toBeInTheDocument() })
test('reschedules using backend slots and communicates Pending status', async () => { api.slots.mockResolvedValue([{start_at:'2035-01-02T10:00:00Z',end_at:'2035-01-02T10:30:00Z'}]); api.reschedule.mockResolvedValue({status:'pending'}); route(<Booking/>, '/patient/book?appointment=a1&doctor=d1'); fireEvent.change(screen.getByLabelText('Date'),{target:{value:'2035-01-02'}}); fireEvent.click(screen.getByText('Load available times')); fireEvent.click(await screen.findByRole('button',{name:/\d{2}:\d{2}/})); fireEvent.click(screen.getByText('Submit request')); await waitFor(()=>expect(api.reschedule).toHaveBeenCalledWith('a1',{doctor_id:'d1',start_at:'2035-01-02T10:00:00Z',end_at:'2035-01-02T10:30:00Z'})); expect(await screen.findByText('Rescheduled as Pending.')).toBeInTheDocument() })
test('shows authorized note', async () => { api.detail.mockResolvedValue({id:'a',start_at:'2035-01-01T09:00:00Z',status:'completed',doctors:{profiles:{full_name:'Dr. Chen'}}}); api.note.mockResolvedValue({note_text:'Follow-up is clear.'}); route(<Detail/>, '/patient/appointments/a'); expect(await screen.findByText('Follow-up is clear.')).toBeInTheDocument() })
test('shows no-note state when the visit-note API returns 404', async () => { api.detail.mockResolvedValue({id:'a',start_at:'2035-01-01T09:00:00Z',status:'completed',doctors:{profiles:{full_name:'Dr. Chen'}}}); api.note.mockRejectedValue(new Error('404')); route(<Detail/>, '/patient/appointments/a'); expect(await screen.findByText('No visit note is available yet.')).toBeInTheDocument() })
test('dashboard uses patient appointment data', async () => { api.appointments.mockResolvedValue([{id:'a',status:'pending',start_at:'2035-01-01T09:00:00Z'}]); route(<PatientDashboard/>); expect((await screen.findAllByText('Pending')).length).toBeGreaterThan(0) })
